"use server";
import { revalidatePath } from "next/cache";
import { supabaseAdmin } from "@/lib/supabase/server";
import { createRestaurantTables } from "@/lib/db/restaurants/tables/createRestaurantTables";
export async function updateTable(restaurantId:string,tableId:string,formData:FormData){const number=Number(formData.get("number"));const name=String(formData.get("name")??"").trim()||null;const zone=String(formData.get("zone")??"").trim()||null;const active=formData.get("active")==="on";if(!restaurantId||!tableId||!Number.isInteger(number)||number<1)throw new Error("Datos de mesa no válidos.");const {error}=await supabaseAdmin.from("tables").update({number,name,zone,active}).eq("id",tableId).eq("restaurant_id",restaurantId);if(error)throw error;const {data:restaurant}=await supabaseAdmin.from("restaurants").select("slug").eq("id",restaurantId).single();if(restaurant?.slug){revalidatePath(`/admin/${restaurant.slug}/tables`);revalidatePath(`/admin/${restaurant.slug}/qr`);}}
export async function createTable(restaurantId:string,slug:string,formData:FormData){const number=Number(formData.get("number"));const name=String(formData.get("name")??"").trim()||null;const zone=String(formData.get("zone")??"").trim()||null;if(!restaurantId||!Number.isInteger(number)||number<1)throw new Error("Número de mesa no válido.");const {data:existing}=await supabaseAdmin.from("tables").select("id").eq("restaurant_id",restaurantId).eq("number",number).maybeSingle();if(existing)throw new Error(`La mesa ${number} ya existe.`);const {error}=await supabaseAdmin.from("tables").insert({restaurant_id:restaurantId,number,name,zone,active:true,qr_token:crypto.randomUUID()});if(error)throw error;revalidatePath(`/admin/${slug}/tables`);revalidatePath(`/admin/${slug}/qr`);}
export async function addRestaurantTables(restaurantId:string,slug:string,formData:FormData){const count=Number(formData.get("count")??0);const generateQr=formData.get("generateQr")==="on";if(!restaurantId)throw new Error("Restaurante no válido.");await createRestaurantTables({restaurantId,count,generateQr});revalidatePath(`/admin/${slug}/tables`);revalidatePath(`/admin/${slug}/qr`);}
export async function toggleTable(restaurantId:string,slug:string,tableId:string,active:boolean){const {error}=await supabaseAdmin.from("tables").update({active}).eq("id",tableId).eq("restaurant_id",restaurantId);if(error)throw error;revalidatePath(`/admin/${slug}/tables`);revalidatePath(`/admin/${slug}/qr`);}
export async function regenerateTableQr(restaurantId:string,slug:string,tableId:string){const {error}=await supabaseAdmin.from("tables").update({qr_token:crypto.randomUUID()}).eq("id",tableId).eq("restaurant_id",restaurantId);if(error)throw error;revalidatePath(`/admin/${slug}/tables`);revalidatePath(`/admin/${slug}/qr`);}
export async function saveTableLayout(restaurantId:string,slug:string,positions:{tableId:string;x:number;y:number}[]){if(!restaurantId||!Array.isArray(positions))throw new Error("Distribución no válida.");for(const p of positions){if(!p.tableId||!Number.isFinite(p.x)||!Number.isFinite(p.y))continue;const {error}=await supabaseAdmin.from("tables").update({position_x:Math.max(0,Math.min(100,p.x)),position_y:Math.max(0,Math.min(100,p.y))}).eq("id",p.tableId).eq("restaurant_id",restaurantId);if(error)throw error;}revalidatePath(`/admin/${slug}/tables`);}
