"use client";

import { useState, useTransition } from "react";
import { closeCashRegister, openCashRegister } from "@/app/admin/[slug]/cash/actions";

type Props = { slug: string; open: null | { id: string; opening_cash: number; opened_at: string }; totals: { cash: number; card: number; sales: number } };
export default function CashRegisterPanel({ slug, open, totals }: Props) {
  const [amount, setAmount] = useState(""); const [closing, setClosing] = useState(false); const [isPending, startTransition] = useTransition(); const expected = open ? Number(open.opening_cash) + totals.cash : 0;
  function submitOpen() { const value = Number(amount.replace(",", ".")); if (!amount.trim() || !Number.isFinite(value) || value < 0) return window.alert("Indica un efectivo inicial válido"); startTransition(async () => { try { await openCashRegister(slug, value); window.location.reload(); } catch (e) { window.alert(e instanceof Error ? e.message : "No se pudo iniciar la caja"); } }); }
  function submitClose() { const value = Number(amount.replace(",", ".")); if (!amount.trim() || !Number.isFinite(value) || value < 0) return window.alert("Indica el efectivo contado"); startTransition(async () => { try { await closeCashRegister(slug, value); window.location.reload(); } catch (e) { window.alert(e instanceof Error ? e.message : "No se pudo cerrar la caja"); } }); }
  if (!open) return <section className="rounded-2xl border border-emerald-500/25 bg-emerald-500/[0.06] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-emerald-400">Caja</p><h2 className="mt-2 text-2xl font-black text-white">Iniciar caja</h2><p className="mt-2 max-w-xl text-sm text-zinc-400">Indica cuánto efectivo hay en el cajón al comenzar la jornada.</p><div className="mt-5 flex max-w-md gap-3"><input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-zinc-700 bg-[#11100f] px-4 py-3 text-lg font-bold text-white outline-none focus:border-emerald-400" placeholder="0,00 €"/><button onClick={submitOpen} disabled={isPending} className="rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white hover:bg-emerald-500 disabled:opacity-50">{isPending ? "Abriendo…" : "Iniciar caja"}</button></div></section>;
  return <section className="rounded-2xl border border-amber-500/25 bg-amber-500/[0.05] p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-amber-400">Caja abierta</p><h2 className="mt-2 text-2xl font-black text-white">Jornada en curso</h2><p className="mt-2 text-sm text-zinc-400">Apertura: <strong className="text-white">{Number(open.opening_cash).toFixed(2)} €</strong></p></div><div className="grid grid-cols-3 gap-2 text-center"><div className="rounded-xl border border-zinc-700 bg-[#181716] px-4 py-3"><p className="text-[9px] uppercase text-zinc-500">Efectivo</p><p className="mt-1 font-black text-white">{totals.cash.toFixed(2)} €</p></div><div className="rounded-xl border border-zinc-700 bg-[#181716] px-4 py-3"><p className="text-[9px] uppercase text-zinc-500">Tarjeta</p><p className="mt-1 font-black text-white">{totals.card.toFixed(2)} €</p></div><div className="rounded-xl border border-zinc-700 bg-[#181716] px-4 py-3"><p className="text-[9px] uppercase text-zinc-500">Total</p><p className="mt-1 font-black text-white">{totals.sales.toFixed(2)} €</p></div></div></div><div className="mt-6 border-t border-zinc-800 pt-5"><button onClick={() => { setAmount(""); setClosing(true); }} className="rounded-xl border border-red-500/40 bg-red-500/10 px-5 py-3 font-bold text-red-200 hover:bg-red-500/20">Hacer cierre de caja</button></div>{closing && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-zinc-700 bg-[#1a1917] p-6 shadow-2xl"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-red-400">Cierre de caja</p><h3 className="mt-2 text-2xl font-black text-white">Cuenta el efectivo</h3><div className="mt-4 space-y-2 text-sm"><p className="text-zinc-400">Efectivo inicial: <strong className="text-white">{Number(open.opening_cash).toFixed(2)} €</strong></p><p className="text-zinc-400">Ventas en efectivo: <strong className="text-white">{totals.cash.toFixed(2)} €</strong></p><p className="text-zinc-400">Efectivo esperado: <strong className="text-white">{expected.toFixed(2)} €</strong></p></div><input autoFocus inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} className="mt-5 w-full rounded-xl border border-zinc-700 bg-[#11100f] px-4 py-3 text-lg font-bold text-white outline-none focus:border-red-400" placeholder="Efectivo contado"/><div className="mt-5 flex gap-3"><button onClick={() => setClosing(false)} className="flex-1 rounded-xl border border-zinc-700 px-4 py-3 font-semibold text-zinc-300">Cancelar</button><button onClick={submitClose} disabled={isPending} className="flex-1 rounded-xl bg-red-600 px-4 py-3 font-bold text-white hover:bg-red-500 disabled:opacity-50">{isPending ? "Cerrando…" : "Cerrar caja"}</button></div></div></div>}</section>;
}
