"use client";

import { useMemo, useState } from "react";

type Register = { id: string; opened_at: string; closed_at: string | null; opening_cash: number; expected_cash: number | null; counted_cash: number | null; cash_difference: number | null; total_cash: number; total_card: number; total_sales: number; payment_count: number };
export default function ReportsClient({ restaurantName, registers }: { slug: string; restaurantName: string; registers: Register[] }) {
  const [selected, setSelected] = useState(registers[0]?.id ?? "");
  const current = useMemo(() => registers.find((r) => r.id === selected) ?? registers[0], [registers, selected]);
  return <main className="min-h-screen bg-[#11100f] text-white"><div className="mx-auto max-w-[1200px] px-5 py-8 sm:px-8"><div className="no-print mb-8"><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-amber-500">Informes</p><h1 className="mt-2 text-4xl font-black">Caja por día</h1><p className="mt-2 text-sm text-zinc-400">Consulta e imprime cualquier cierre de caja histórico.</p></div>{registers.length === 0 ? <div className="rounded-2xl border border-zinc-800 bg-[#181716] p-8 text-zinc-500">Todavía no hay cierres de caja.</div> : <><div className="no-print mb-5 flex flex-col gap-3 sm:flex-row"><select value={current?.id} onChange={(e) => setSelected(e.target.value)} className="flex-1 rounded-xl border border-zinc-700 bg-[#181716] px-4 py-3 font-semibold text-white">{registers.map((r) => <option key={r.id} value={r.id}>{new Date(r.opened_at).toLocaleDateString("es-ES")} · {r.closed_at ? "Cerrada" : "Abierta"}</option>)}</select><button onClick={() => window.print()} className="rounded-xl bg-amber-600 px-6 py-3 font-bold text-white hover:bg-amber-500">🖨️ Imprimir caja</button></div>{current && <article className="rounded-2xl border border-zinc-800 bg-[#181716] p-6 sm:p-8 print:border-0 print:bg-white print:p-0 print:text-black"><div className="border-b border-zinc-700 pb-5 print:border-black"><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-500 print:text-black">CIERRE DE CAJA</p><h2 className="mt-2 text-3xl font-black">{restaurantName}</h2><p className="mt-1 text-sm text-zinc-400 print:text-black">{new Date(current.opened_at).toLocaleDateString("es-ES")}</p></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Metric label="Efectivo inicial" value={current.opening_cash}/><Metric label="Ventas efectivo" value={current.total_cash}/><Metric label="Ventas tarjeta" value={current.total_card}/><Metric label="Ventas totales" value={current.total_sales}/><Metric label="Efectivo esperado" value={current.expected_cash}/><Metric label="Efectivo contado" value={current.counted_cash}/><Metric label="Diferencia" value={current.cash_difference}/><Metric label="Operaciones" value={current.payment_count} money={false}/></div><div className="mt-8 border-t border-zinc-700 pt-5 text-sm text-zinc-500 print:border-black print:text-black"><p>Apertura: {new Date(current.opened_at).toLocaleString("es-ES")}</p><p className="mt-1">Cierre: {current.closed_at ? new Date(current.closed_at).toLocaleString("es-ES") : "Caja todavía abierta"}</p></div></article>}</>}</div><style jsx global>{`@media print { body { background: white !important; } .no-print { display: none !important; } }`}</style></main>;
}
function Metric({ label, value, money = true }: { label: string; value: number | null; money?: boolean }) { return <div className="rounded-xl border border-zinc-700 bg-[#11100f] p-4 print:border-black print:bg-white"><p className="text-xs text-zinc-500 print:text-black">{label}</p><p className="mt-1 text-2xl font-black">{value == null ? "—" : money ? `${Number(value).toFixed(2)} €` : Number(value)}</p></div>; }
